Opifer\CmsBundle\Entity\AttachmentValue:
    type: entity
    table: attachment_value
    oneToOne:
        attachment:
            targetEntity: Opifer\MediaBundle\Model\MediaInterface
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                attachment_id:
                    referencedColumnName: id
            orphanRemoval: false
