Opifer\CmsBundle\Entity\ContentType:
    type: entity
    table: content_type
    gedmo:
      soft_deleteable:
        field_name: deletedAt
        time_aware: false
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 128
            unique: false
            nullable: false
            precision: 0
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: created_at
            gedmo:
              timestampable:
                on: create
        updatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: updated_at
            gedmo:
              timestampable:
                on: update
        deletedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    manyToOne:
        schema:
            targetEntity: Opifer\EavBundle\Model\SchemaInterface
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                schema_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        content:
            targetEntity: Opifer\ContentBundle\Model\ContentInterface
            cascade: {  }
            fetch: LAZY
            mappedBy: contentType
            inversedBy: null
            orphanRemoval: false
            orderBy:
                id: DESC
    lifecycleCallbacks: {  }
