Opifer\CmsBundle\Entity\FormValue:
    type: entity
    table: form_value
    manyToOne:
        form:
            targetEntity: Opifer\FormBundle\Model\FormInterface
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                form_id:
                    referencedColumnName: id
            orphanRemoval: false
