parameters:
    opifer.eav.address_value_provider.class: Opifer\EavBundle\ValueProvider\AddressValueProvider
    opifer.eav.checklist_value_provider.class: Opifer\EavBundle\ValueProvider\ChecklistValueProvider
    opifer.eav.form_value_provider.class: Opifer\EavBundle\ValueProvider\FormValueProvider
    opifer.eav.html_value_provider.class: Opifer\EavBundle\ValueProvider\HtmlValueProvider
    opifer.eav.integer_value_provider.class: Opifer\EavBundle\ValueProvider\IntegerValueProvider
    opifer.eav.media_value_provider.class: Opifer\EavBundle\ValueProvider\MediaValueProvider
    opifer.eav.nested_value_provider.class: Opifer\EavBundle\ValueProvider\NestedValueProvider
    opifer.eav.query_value_provider.class: Opifer\EavBundle\ValueProvider\QueryValueProvider
    opifer.eav.select_value_provider.class: Opifer\EavBundle\ValueProvider\SelectValueProvider
    opifer.eav.string_value_provider.class: Opifer\EavBundle\ValueProvider\StringValueProvider
    opifer.eav.text_value_provider.class: Opifer\EavBundle\ValueProvider\TextValueProvider
    opifer.eav.twitter_value_provider.class: Opifer\EavBundle\ValueProvider\TwitterValueProvider

services:
    opifer.eav.html_value_provider:
        class: %opifer.eav.html_value_provider.class%
        tags:
            - { name: opifer.eav.value_provider, alias: html }

    opifer.eav.integer_value_provider:
        class: %opifer.eav.integer_value_provider.class%
        tags:
            - { name: opifer.eav.value_provider, alias: integer }

    opifer.eav.media_value_provider:
        class: %opifer.eav.media_value_provider.class%
        arguments: [%opifer_eav.media_class%]
        tags:
            - { name: opifer.eav.value_provider, alias: media }

    opifer.eav.query_value_provider:
        class: %opifer.eav.query_value_provider.class%
        tags:
            - { name: opifer.eav.value_provider, alias: query }

    opifer.eav.string_value_provider:
        class: %opifer.eav.string_value_provider.class%
        tags:
            - { name: opifer.eav.value_provider, alias: string }

    opifer.eav.text_value_provider:
        class: %opifer.eav.text_value_provider.class%
        tags:
            - { name: opifer.eav.value_provider, alias: text }

    opifer.eav.nested_value_provider:
        class: %opifer.eav.nested_value_provider.class%
        arguments: [%opifer_eav.nestable_class%]
        tags:
            - { name: opifer.eav.value_provider, alias: nested }

    opifer.eav.select_value_provider:
        class: %opifer.eav.select_value_provider.class%
        arguments: [%opifer_eav.option_class%]
        tags:
            - { name: opifer.eav.value_provider, alias: select }

    opifer.eav.checklist_value_provider:
         class: %opifer.eav.checklist_value_provider.class%
         arguments: [%opifer_eav.option_class%]
         tags:
             - { name: opifer.eav.value_provider, alias: checklist }

    opifer.eav.datetime_value_provider:
        class: Opifer\EavBundle\ValueProvider\DatetimeValueProvider
        tags:
            - { name: opifer.eav.value_provider, alias: datetime }

    # opifer.eav.date_value_provider:
    #     class: Opifer\EavBundle\ValueProvider\DateValueProvider
    #     tags:
    #         - { name: opifer.eav.value_provider, alias: date }

    opifer.eav.form_value_provider:
         class: %opifer.eav.form_value_provider.class%
         arguments: [%opifer_eav.template_class%]
         tags:
             - { name: opifer.eav.value_provider, alias: form }
             
#    opifer.eav.twitter_value_provider:
#        class: %opifer.eav.twitter_value_provider.class%
#        tags:
#            - { name: opifer.eav.value_provider, alias: twitter }
