opifer_form_form_index:
    path: /form
    defaults: { _controller: OpiferFormBundle:Form:index }

opifer_form_form_create:
    path: /form/create
    defaults: { _controller: OpiferFormBundle:Form:create }

opifer_form_form_edit:
    path: /form/edit/{id}
    defaults: { _controller: OpiferFormBundle:Form:edit }

opifer_form_form_delete:
    path: /form/delete/{id}
    defaults: { _controller: OpiferFormBundle:Form:delete }

opifer_form_post_index:
    path: /form/{formId}/posts
    defaults: { _controller: OpiferFormBundle:Post:index }
    requirements:
        formId: \d+

opifer_form_post_view:
    path: /form/posts/{id}
    defaults: { _controller: OpiferFormBundle:Post:view }

opifer_form_post_delete:
    path: /form/posts/delete/{id}
    defaults: { _controller: OpiferFormBundle:Post:delete }
