opifer_content_api_content:
    path: /contents
    defaults: { _controller: OpiferContentBundle:Api/Content:index }
    methods: [GET]
    options:
        expose: true

opifer_content_api_content_ids:
    path: /contents/ids/{ids}
    defaults: { _controller: OpiferContentBundle:Api/Content:ids }
    methods: [GET]
    options:
        expose: true

opifer_content_api_content_view:
    path: /contents/{id}
    defaults: { _controller: OpiferContentBundle:Api/Content:view }
    methods: [GET]
    options:
        expose: true

opifer_content_api_content_delete:
    path: /contents/{id}
    defaults: { _controller: OpiferContentBundle:Api/Content:delete }
    methods: [DELETE]
    options:
        expose: true

opifer_content_api_directory:
    path: /directories
    defaults: { _controller: OpiferContentBundle:Api/Directory:index }
    methods: [GET]
    options:
        expose: true

opifer_content_api_layout:
    path: /layouts
    defaults: { _controller: OpiferContentBundle:Api/Layout:index }
    methods: [GET]
    options:
        expose: true

opifer_content_api_pagemanager_create_block:
    path: /pagemanager/createblock/{type}/{parentId}/{placeholder}
    defaults: { _controller: OpiferContentBundle:Api/PageManager:createBlock }
    methods: [POST]
    options:
        expose: true

opifer_content_api_pagemanager_move_block:
    path: /pagemanager/moveblock
    defaults: { _controller: OpiferContentBundle:Api/PageManager:moveBlock }
    methods: [POST]
    options:
        expose: true

opifer_content_api_pagemanager_view_block:
    path: /pagemanager/viewblock/{id}
    defaults: { _controller: OpiferContentBundle:Api/PageManager:viewBlock }
    methods: [GET]
    options:
        expose: true

opifer_content_api_pagemanager_remove_block:
    path: /pagemanager/removeblock/{id}
    defaults: { _controller: OpiferContentBundle:Api/PageManager:removeBlock }
    methods: [DELETE]
    options:
        expose: true
