parameters:
    opifer.media.file_provider.class: Opifer\MediaBundle\Provider\FileProvider
    opifer.media.image_provider.class: Opifer\MediaBundle\Provider\ImageProvider
    opifer.media.youtube_provider.class: Opifer\MediaBundle\Provider\YoutubeProvider
    opifer.media.media_manager.class: Opifer\MediaBundle\Model\MediaManager

services:
    opifer.media.media_manager.default:
        class: %opifer.media.media_manager.class%
        arguments: [@doctrine.orm.entity_manager, %opifer_media.model.class%]

    opifer.media.listener.media_listener:
        class: Opifer\MediaBundle\EventListener\MediaListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber }

    # Serializer
    opifer.media.handler.serialization:
        class: Opifer\MediaBundle\EventListener\Serializer\MediaEventSubscriber
        arguments: [@liip_imagine.cache.manager, @liip_imagine.filter.configuration, @opifer.media.provider.pool]
        tags:
            - { name: jms_serializer.event_subscriber }

    # Form Types
    opifer.media.form.dropzone:
        class: Opifer\MediaBundle\Form\Type\DropzoneType
        arguments: [@opifer.media.media_manager]
        tags:
            - { name: form.type, alias: dropzone }

    opifer.media.form.mediapicker:
        class: Opifer\MediaBundle\Form\Type\MediaPickerType
        arguments: [@opifer.media.provider.pool, @doctrine, @property_accessor]
        tags:
            - { name: form.type, alias: mediapicker }

    # Providers
    opifer.media.provider.pool:
        class: Opifer\MediaBundle\Provider\Pool

    opifer.media.file_provider:
        class: %opifer.media.file_provider.class%
        arguments: [@gaufrette.file_storage_filesystem, @translator, @router]
        tags:
            - { name: opifer.media.provider, alias: file }

    opifer.media.image_provider:
        class: %opifer.media.image_provider.class%
        arguments: [@gaufrette.file_storage_filesystem, @translator, @router]
        tags:
            - { name: opifer.media.provider, alias: image }

    opifer.media.youtube_provider:
        class: %opifer.media.youtube_provider.class%
        arguments: [@opifer.media.media_manager, @translator, %opifer_media.providers.youtube.api_key%]
        tags:
            - { name: opifer.media.provider, alias: youtube }

    # Image processors
    opifer.media.aws_s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                key: %opifer_media.storages.aws_s3.key%
                secret: %opifer_media.storages.aws_s3.secret%
                region: %opifer_media.storages.aws_s3.region%

    liip_imagine.data.loader.stream.photo_storage:
        class: "%liip_imagine.binary.loader.stream.class%"
        arguments:
            - 'gaufrette://file_storage/'
        tags:
            - { name: 'liip_imagine.binary.loader', loader: 'stream.file_storage' }

    opifer.imagine.cache.resolver.amazon_s3:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\AwsS3Resolver
        arguments:
            - "@opifer.media.aws_s3.client"
            - "%opifer_media.storages.aws_s3.bucket%"
            - "public-read"
            - { https: true }
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: 'aws_storage' }
        calls:
            - [setCachePrefix, ["cache"]]
            - [setPutOption, ['CacheControl', 'max-age=86400' ]]

    opifer.imagine.cache.resolver.amazon_s3.proxy:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\ProxyResolver
        arguments:
            - "@opifer.imagine.cache.resolver.amazon_s3"
            - %opifer_media.storages.aws_s3.proxies%
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: 'proxy_aws_storage' }
