language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer selfupdate
    - composer install --dev --prefer-dist --no-interaction

script: phpunit

notifications:
    hipchat: af0VgAPun/Ncw5DS9s5tsusDRZC+SVzj9ra3Sw/A/enbbEI5/DKKh9+D/u+i/6pAnuMfQCHOI3Tea/bvwrkXrSl5b+n8CMD5uuxpwmPEVcyHEdpI25WoayBQXkbfn8hGHb3fW+v0Nt9APlUMvZUuMnDh609b9S7P5IlkBXMeatk=
