language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_DEPRECATIONS_HELPER=weak

before_script:
  - composer selfupdate
  - composer install -n

script: phpunit --coverage-text

branches:
  only:
    - master
    - develop
