services:
    opifer.subscription_manager:
        class: Opifer\MailingListBundle\Manager\SubscriptionManager
        arguments: ['@doctrine.orm.default_entity_manager', '@service_container']
        tags:
            - { name: opifer.subscription_manager }
