framework:
    validation:
        cache: apc

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: error

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/(api|accept-cookies)':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+', '^http://127.0.0.1:[0-9]+', '^http://[a-z0-9-]+.dev:[0-9]+']
            allow_headers: ['origin', 'x-custom-auth', 'authorization', 'content-type', 'accept', 'x-requested-with']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
