# Routing used by multiple bundles
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security_check:
    pattern: /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    methods: [POST]

fos_user_security_logout:
    pattern: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

# Bazinga Translator Routing
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

# Opifer bundle routing

opifer_eav:
    resource: "@OpiferEavBundle/Resources/config/routing.yml"
    prefix:   /admin

opifer_eav_form_submit:
    pattern: /eav/form/submit/{valueId}
    defaults:
        _controller: OpiferEavBundle:Form:submit
    requirements:
        valueId: "\d+"
    methods: [POST]

opifer_rules_engine:
    resource: "@OpiferRulesEngineBundle/Resources/config/routing.yml"
    prefix:   /

opifer_redirect:
    resource: "@OpiferContentBundle/Resources/config/routing.yml"
    prefix: /admin/redirects

# API routes
opifer_content:
    resource: "@OpiferContentBundle/Resources/config/routing.yml"
    prefix:   /admin

opifer_media:
    resource: "@OpiferMediaBundle/Resources/config/routing.yml"
    prefix:   /admin

##### SITEBUNDLE ######
#opifer.site.home:
#    pattern:  /
#    defaults: { _controller: OpiferSiteBundle:Page:home }
#    options: {sitemap: true}

#opifer.site.profile:
#    resource: "@OpiferSiteBundle/Controller/ProfileController.php"
#    type:     annotation

opifer_cms_exception:
    resource: "@OpiferCmsBundle/Controller/Front/ExceptionController.php"
    type:     annotation

#opifer.site.change_password:
#    pattern:  /profile/change-password
#    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
#    methods:  [GET,POST]
#
#opifer.site.content:
#    resource: "@OpiferSiteBundle/Controller/ContentController.php"
#    type:     annotation

# Authentication
#opifer.site.login:
#    pattern:  /login
#    defaults: { _controller: FOSUserBundle:Security:login }

#opifer.site.register:
#    pattern:  /register
#    defaults: { _controller: OpiferSiteBundle:Authentication:authenticate }
#    options: { sitemap: true }
#
#opifer.site.security.login:
#    pattern:  /authenticate/login
#    defaults: { _controller: OpiferSiteBundle:Security:login }
#
#opifer.site.registration.register:
#    pattern:  /authenticate/register
#    defaults: { _controller: OpiferSiteBundle:Registration:register }
#
#opifer.site.registration.check_mail:
#    pattern:  /register/check-email
#    defaults: { _controller: OpiferSiteBundle:Registration:checkEmail }
#    methods:  [GET]
#
#opifer.site.registration.confirm:
#    pattern:  /register/confirm/{token}
#    defaults: { _controller: OpiferSiteBundle:Registration:confirm }
#    methods:  [GET]
#
#opifer.site.registration.confirmed:
#    pattern:  /register/confirmed
#    defaults: { _controller: OpiferSiteBundle:Registration:confirmed }
#    methods:  [GET]

# Resetting

#opifer.site.resetting.request:
#    pattern:  /password/reset
#    defaults: { _controller: OpiferSiteBundle:Resetting:request }
#    methods:  [GET]
#
#opifer.site.resetting.send_email:
#    pattern:  /password/reset/send-email
#    defaults: { _controller: OpiferSiteBundle:Resetting:sendEmail }
#    methods:  [POST]
#
#opifer.site.resetting.check_email:
#    pattern:  /password/reset/check-email
#    defaults: { _controller: OpiferSiteBundle:Resetting:checkEmail }
#    methods:  [GET]
#
#opifer.site.resetting.reset:
#    pattern:  /password/reset/reset/{token}
#    defaults: { _controller: OpiferSiteBundle:Resetting:reset }
#    methods:  [GET,POST]

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

# Third party bundle routing fallbacks

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

#fos_user_resetting_request:
#    pattern:  /password/reset
#    defaults: { _controller: OpiferSiteBundle:Resetting:request }
#    methods:  [GET]
#
#fos_user_resetting_send_email:
#    pattern:  /password/reset/send-email
#    defaults: { _controller: OpiferSiteBundle:Resetting:sendEmail }
#    methods:  [POST]
#
#fos_user_resetting_check_email:
#    pattern:  /password/reset/check-email
#    defaults: { _controller: OpiferSiteBundle:Resetting:checkEmail }
#    methods:  [GET]
#
#fos_user_resetting_reset:
#    pattern:  /password/reset/reset/{token}
#    defaults: { _controller: OpiferSiteBundle:Resetting:reset }
#    methods:  [GET,POST]
#
#fos_user_profile_show:
#    pattern:  /profile
#    defaults: { _controller: OpiferSiteBundle:Profile:edit }
#    methods:  [GET]
#
#fos_user_profile_edit:
#    pattern:  /profile
#    defaults: { _controller: OpiferSiteBundle:Profile:edit }

fos_user_change_password:
    pattern:  /change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods:  [GET,POST]

##### END SITEBUNDLE ######

_opifer_admin:
    resource: "routing_admin.yml"
    prefix:   /admin
