opifer_cms_dashboard:
    resource: "@OpiferCmsBundle/Controller/DashboardController.php"
    type:     annotation

opifer_cms_menu:
    resource: "@OpiferCmsBundle/Controller/MenuController.php"
    type:     annotation

opifer_cms_setting:
    resource: "@OpiferCmsBundle/Controller/SettingController.php"
    type:     annotation

opifer_cms_command:
    resource: "@OpiferCmsBundle/Controller/CommandController.php"
    type:     annotation

opifer_cms_user:
    resource: "@OpiferCmsBundle/Controller/UserController.php"
    type:     annotation

opifer_cms_template_delete:
    path: /templates/delete/{id}
    defaults: {_controller: OpiferCmsBundle:Template:delete}
    requirements:
        id: "\d+"

opifer_ckeditor_content:
    path: /ckeditor/content
    defaults: { _controller: OpiferCmsBundle:CKEditor:content }
    options:
        expose: true

opifer_ckeditor_media:
    path: /ckeditor/media
    defaults: { _controller: OpiferCmsBundle:CKEditor:media }
    options:
        expose: true

opifer_form_admin:
    resource: "@OpiferFormBundle/Resources/config/routing_admin.yml"

opifer_eav_admin:
    resource: "@OpiferEavBundle/Resources/config/routing.yml"

opifer_content_admin:
    resource: "@OpiferContentBundle/Resources/config/routing.yml"

opifer_media_admin:
    resource: "@OpiferMediaBundle/Resources/config/routing.yml"

opifer_redirect_admin:
    resource: "@OpiferRedirectBundle/Resources/config/routing.yml"
    prefix: /redirects

# Users
fos_user_security_login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix:   /group

# Place all routes above the crud routing, to allow easy overriding
opifer_crud:
    resource: "@OpiferCrudBundle/Resources/config/routing.yml"
    prefix:   /
